### ISSUE TITLE
Print support

### ISSUE THREAD

**Issue by Revengance1024** [poetools/BetrayalCheatSheet#11]
Print support is just a few lines away

```
@media print {
    @page {
        size: landscape;
    }

    #landing-description h2,
    #colour-selectors,
    #community-widgets,
    #footer {
        display: none;
    }
}
```
(In src/components/BetrayalCheatSheet.css)

Before: https://i.imgur.com/fJrt4Ga.png
After: https://i.imgur.com/T4a7bNI.png

P.S. Love the tool

**Comment by Multigrain** [comment]
Looks great. Never thought about printing it out as I've always had it on another monitor while playing. Thanks for the contribution.
