### ISSUE TITLE
Update to 3.18

### ISSUE THREAD

**Issue by KuryKat** [poetools/BetrayalCheatSheet#13]
Maybe this will help:
https://www.reddit.com/r/pathofexile/comments/ukyevb/318_updated_betrayal_cheatsheet/

**Comment by Multigrain** [comment]
Looking at that post I don't believe there are any changes to betrayal this league. So it should be the same as the last update 3.17. If I missed anything let me know, otherwise I'll update the footer to 3.18. Thanks for the post.

**Comment by KuryKat** [comment]
I'm still new so I'll believe your knowledge
