### ISSUE TITLE
Update to 3.20

### ISSUE THREAD

**Issue by Tikey14** [poetools/BetrayalCheatSheet#14]
Hi!

The cheat sheet is outdated. It should have the following changes to be updated.

1. Janus - Research: The Icon for item for expedition is perandus coin, it should be updated. Maybe the one in [poe](https://poe.ninja/challenge/artifacts)
2. Janus - Intervetion: The icon seems off. Here https://poe.ninja/challenge/scarabs it could be taken the icon from **Polished Expedition Scarab**
3. Ricker - Research: The Icon and the text should are old. It should be updated to **Trapped chest with Splinter/Essences/Fossils/Catalyst items.**

Hope it's not a big deal

**Comment by Multigrain** [comment]
Yeah, I'll update them this weekend. I skimmed updates to see if there were any other big ones and I think Leo - Research has also changed. If there are any other ones I've missed let me know.
