### ISSUE TITLE
Janus Changed

### ISSUE THREAD

**Issue by B14d3r11** [poetools/BetrayalCheatSheet#8]
Can you make it so Janus no longer has Perandus but has the new expedition stuff?

**Comment by Multigrain** [comment]
Sure, I haven't been playing this league so if there are any other changes let me know. I'm just going to update the text for now since I don't have my photo editing setup on this computer.

**Comment by B14d3r11** [comment]
![image](https://user-images.githubusercontent.com/28051452/140469435-8618aaf3-af53-4968-b7e9-4108f03cf86c.png)
The bottom two of his stuff changed to this.
